name: WireUi Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Execute tests (Unit and Browser tests) via PHPUnit
        env:
          RUNNING_IN_CI: true
        run: vendor/bin/phpunit
